### ISSUE TITLE
Error running test command

### ISSUE THREAD

**Issue by cairoapcampos** [veins/veins_hetvnet#1]
I apologize for bothering you again. But I couldn't understand the runtime error. I am using Instant Veins 5.0-alpha2 i1.

Problem:

veins:~/src/veins_hetvnet/examples/veins_hetvnet% ./run -d -u cmdenv | grep "HetVNetDemoApp::handleMessage"
./run: 25: exec: ../../run: not found
zsh: exit 127   ./run -d -u cmdenv | 
zsh: exit 1     grep --color=auto "HetVNetDemoApp::handleMessage"

**Comment by sommer** [comment]
I don't think the issue tracker is a good place for support requests. Would you mind moving this discussion to the OMNeT++ mailing list, SuperUser, or StackOverflow (depending on the topic) (and adding a link from this thread)?

**Comment by cairoapcampos** [comment]
Sorry for the inconvenience. Question moved to StackOverflow:

https://stackoverflow.com/questions/57629722/error-running-test-command-in-veins-hetvnet
